name: Publish Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  ghcr_publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["node-sandbox"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log-in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push ${{ matrix.image }}
        run: ./build.sh ${{ matrix.image }} --push
